/**
 * Translation language catalog.
 *
 * Values match Google Translate-compatible language codes. Labels live here so
 * settings menus, popup controls, and tooltips can show names instead of raw
 * codes such as "ko" or "zh-CN".
 */
export type LanguageOption = readonly [value: string, label: string];

export const LANGUAGE_OPTIONS: readonly LanguageOption[] = [
  ['en', 'English'],
  ['ja', 'Japanese'],
  ['id', 'Indonesian'],
  ['ko', 'Korean'],
  ['es', 'Spanish'],
  ['pt', 'Portuguese'],
  ['ru', 'Russian'],
  ['fr', 'French'],
  ['de', 'German'],
  ['it', 'Italian'],
  ['zh-CN', 'Chinese (Simplified)'],
  ['zh-TW', 'Chinese (Traditional)'],
  ['af', 'Afrikaans'],
  ['sq', 'Albanian'],
  ['am', 'Amharic'],
  ['ar', 'Arabic'],
  ['hy', 'Armenian'],
  ['az', 'Azerbaijani'],
  ['eu', 'Basque'],
  ['be', 'Belarusian'],
  ['bn', 'Bengali'],
  ['bs', 'Bosnian'],
  ['bg', 'Bulgarian'],
  ['ca', 'Catalan'],
  ['ceb', 'Cebuano'],
  ['ny', 'Chichewa'],
  ['co', 'Corsican'],
  ['hr', 'Croatian'],
  ['cs', 'Czech'],
  ['da', 'Danish'],
  ['nl', 'Dutch'],
  ['eo', 'Esperanto'],
  ['et', 'Estonian'],
  ['tl', 'Filipino'],
  ['fi', 'Finnish'],
  ['fy', 'Frisian'],
  ['gl', 'Galician'],
  ['ka', 'Georgian'],
  ['el', 'Greek'],
  ['gu', 'Gujarati'],
  ['ht', 'Haitian Creole'],
  ['ha', 'Hausa'],
  ['haw', 'Hawaiian'],
  ['iw', 'Hebrew'],
  ['hi', 'Hindi'],
  ['hmn', 'Hmong'],
  ['hu', 'Hungarian'],
  ['is', 'Icelandic'],
  ['ig', 'Igbo'],
  ['ga', 'Irish'],
  ['jw', 'Javanese'],
  ['kn', 'Kannada'],
  ['kk', 'Kazakh'],
  ['km', 'Khmer'],
  ['rw', 'Kinyarwanda'],
  ['ku', 'Kurdish (Kurmanji)'],
  ['ky', 'Kyrgyz'],
  ['lo', 'Lao'],
  ['la', 'Latin'],
  ['lv', 'Latvian'],
  ['lt', 'Lithuanian'],
  ['lb', 'Luxembourgish'],
  ['mk', 'Macedonian'],
  ['mg', 'Malagasy'],
  ['ms', 'Malay'],
  ['ml', 'Malayalam'],
  ['mt', 'Maltese'],
  ['mi', 'Maori'],
  ['mr', 'Marathi'],
  ['mn', 'Mongolian'],
  ['my', 'Myanmar (Burmese)'],
  ['ne', 'Nepali'],
  ['no', 'Norwegian'],
  ['or', 'Odia (Oriya)'],
  ['ps', 'Pashto'],
  ['fa', 'Persian'],
  ['pl', 'Polish'],
  ['pa', 'Punjabi'],
  ['ro', 'Romanian'],
  ['sm', 'Samoan'],
  ['gd', 'Scots Gaelic'],
  ['sr', 'Serbian'],
  ['st', 'Sesotho'],
  ['sn', 'Shona'],
  ['sd', 'Sindhi'],
  ['si', 'Sinhala'],
  ['sk', 'Slovak'],
  ['sl', 'Slovenian'],
  ['so', 'Somali'],
  ['su', 'Sundanese'],
  ['sw', 'Swahili'],
  ['sv', 'Swedish'],
  ['tg', 'Tajik'],
  ['ta', 'Tamil'],
  ['tt', 'Tatar'],
  ['te', 'Telugu'],
  ['th', 'Thai'],
  ['tr', 'Turkish'],
  ['tk', 'Turkmen'],
  ['uk', 'Ukrainian'],
  ['ur', 'Urdu'],
  ['ug', 'Uyghur'],
  ['uz', 'Uzbek'],
  ['vi', 'Vietnamese'],
  ['cy', 'Welsh'],
  ['xh', 'Xhosa'],
  ['yi', 'Yiddish'],
  ['yo', 'Yoruba'],
  ['zu', 'Zulu']
];

export function getLanguageLabel(languageCode: string): string {
  return LANGUAGE_OPTIONS.find(([value]) => value === languageCode)?.[1] || languageCode;
}
